### ISSUE TITLE
如若将 pathname 加上一个伪静态的后缀，返回的数据 content-type 就发生改变

### ISSUE THREAD

**Issue by lfire** [hbxeagle/http-mock-json-server#2]
如：
“pathname": "/api/getUser.html"

返回的数据 content-type 是 text/html
我希望是 application/json  或是，我可以单独的指定配置 

另外，如果将后缀 html  去除，则是以 json 格式返回

**Comment by hbxeagle** [comment]
content-type是依据后缀做的处理，我尽快发一版，默认使用json，同时支持配置需求。

**Comment by lfire** [comment]
nice

**Comment by hbxeagle** [comment]
已经发布 v0.2.3，在mock.json中新增了一个 ‘contentType’，支持自定义某个path的配置content-type。
